// import 'package:baseproject/model/article.dart';

List<String> articles = [
  """
<h3 class="new-article__title" data-auto="article-name"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Tricks to be the best on Friday Night Funkin</font></font></h3>
<p><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Friday Night Funkin '</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> is the fun </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">free rhythm game</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> that everyone's talking about. </font><font style="vertical-align: inherit;">Inspired by classics of the genre such as the Hatsune Miku games, PaRappa the Rapper or DDR (Dance Dance Revolution), Friday Night Funkin 'puts us in the shoes of Boyfriend, a young man who must fight in crazy </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">musical duels</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> to get a kiss from his girlfriend, Girlfriend. </font><font style="vertical-align: inherit;">But the thing is not so simple, after these combats at the blow of the microphone is Daddy Dearest, the father of the young woman and an ex-rock star ready to do anything to erase you from the map.</font></font></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">With this fun premise, Friday Night Funkin 'starts, a game that </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">offers new musical challenges every week</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> . </font><font style="vertical-align: inherit;">Although don't be fooled by its charming and innocent graphics, the game is </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">really difficult</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> . </font><font style="vertical-align: inherit;">Fortunately, at Softonic we have made a small guide of </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">tips and tricks for Friday Night Funkin '</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> so that you can defeat all your rivals without much effort. </font><font style="vertical-align: inherit;">Here we go!</font></font></p>
<p><img loading="lazy" class="alignnone wp-image-218693" src="https://articles-img.sftcdn.net/images/w_845,h_298/v1610650304/friday_night_funkin_1_uovxay/friday_night_funkin_1_uovxay.jpg" alt="Friday night funkin '" width="845" height="298" srcset="https://articles-img.sftcdn.net/images/v1610650304/friday_night_funkin_1_uovxay/friday_night_funkin_1_uovxay.jpg 845w, https://articles-img.sftcdn.net/images/w_300,h_106,c_scale/v1610650304/friday_night_funkin_1_uovxay/friday_night_funkin_1_uovxay-1-300x106.jpg 300w, https://articles-img.sftcdn.net/images/w_768,h_271,c_scale/v1610650304/friday_night_funkin_1_uovxay/friday_night_funkin_1_uovxay-1-768x271.jpg 768w, https://articles-img.sftcdn.net/images/w_150,h_53,c_scale/v1610650304/friday_night_funkin_1_uovxay/friday_night_funkin_1_uovxay-1-150x53.jpg 150w" sizes="(max-width: 709px) 85vw, (max-width: 909px) 67vw, (max-width: 1362px) 62vw, 840px"></p>
""",
  """
<h3><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">1. Correctly place your hands on the keyboard</font></font></strong></h3>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">A fundamental trick to playing Friday Night Funkin 'is </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">knowing how to position your fingers correctly on the keyboard</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> . </font><font style="vertical-align: inherit;">The game works with both the WASD keys and the arrow keys and it is usual that when we start playing we opt for one of the two controls. </font><font style="vertical-align: inherit;">Big mistake!</font></font></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">The most comfortable and effective way to play Friday Night Funkin 'is to use both hands on both controls. </font><font style="vertical-align: inherit;">A very effective trick is to put the </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">left hand on the A and S keys</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> , while the </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">right hand is on the up and right keys</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> . </font><font style="vertical-align: inherit;">This will make it much easier for you to hit all the notes and win the battles.</font></font></p>
<p><img loading="lazy" class="alignnone wp-image-218694" src="https://articles-img.sftcdn.net/images/w_600,h_220/v1610651458/teclado_fnf_r9vhr6/teclado_fnf_r9vhr6.jpg" alt="Friday Night Funkin 'Keyboard" width="600" height="220" srcset="https://articles-img.sftcdn.net/images/v1610651458/teclado_fnf_r9vhr6/teclado_fnf_r9vhr6.jpg 1230w, https://articles-img.sftcdn.net/images/w_300,h_110,c_scale/v1610651458/teclado_fnf_r9vhr6/teclado_fnf_r9vhr6-300x110.jpg 300w, https://articles-img.sftcdn.net/images/w_1024,h_375,c_scale/v1610651458/teclado_fnf_r9vhr6/teclado_fnf_r9vhr6-1024x375.jpg 1024w, https://articles-img.sftcdn.net/images/w_768,h_281,c_scale/v1610651458/teclado_fnf_r9vhr6/teclado_fnf_r9vhr6-768x281.jpg 768w, https://articles-img.sftcdn.net/images/w_1200,h_439,c_scale/v1610651458/teclado_fnf_r9vhr6/teclado_fnf_r9vhr6-1200x439.jpg 1200w, https://articles-img.sftcdn.net/images/w_150,h_55,c_scale/v1610651458/teclado_fnf_r9vhr6/teclado_fnf_r9vhr6-150x55.jpg 150w" sizes="(max-width: 709px) 85vw, (max-width: 909px) 67vw, (max-width: 984px) 61vw, (max-width: 1362px) 45vw, 600px"></p>
""",
  """
<div id="NativeAd"></div>
""",
  """
<h3><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">2. Play the tutorial</font></font></strong></h3>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">It is very common that when we start playing Friday Night Funkin 'we skip the tutorial and jump straight into the game. </font><font style="vertical-align: inherit;">However, the tutorial is really </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">useful to practice</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> and </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">understand how it works</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> . </font><font style="vertical-align: inherit;">So, don't make Girlfriend ugly and spend a few minutes explaining to you step by step how to defeat your rivals.</font></font></p>
<p><img loading="lazy" class="alignnone wp-image-218695" src="https://articles-img.sftcdn.net/images/w_600,h_350/v1610651855/friday_night_funkin_2_uv0lc0/friday_night_funkin_2_uv0lc0.jpg" alt="Friday Night Funkin 'Tutorial" width="600" height="350" srcset="https://articles-img.sftcdn.net/images/v1610651855/friday_night_funkin_2_uv0lc0/friday_night_funkin_2_uv0lc0.jpg 901w, https://articles-img.sftcdn.net/images/w_300,h_175,c_scale/v1610651855/friday_night_funkin_2_uv0lc0/friday_night_funkin_2_uv0lc0-1-300x175.jpg 300w, https://articles-img.sftcdn.net/images/w_768,h_448,c_scale/v1610651855/friday_night_funkin_2_uv0lc0/friday_night_funkin_2_uv0lc0-1-768x448.jpg 768w, https://articles-img.sftcdn.net/images/w_150,h_87,c_scale/v1610651855/friday_night_funkin_2_uv0lc0/friday_night_funkin_2_uv0lc0-1-150x87.jpg 150w" sizes="(max-width: 709px) 85vw, (max-width: 909px) 67vw, (max-width: 984px) 61vw, (max-width: 1362px) 45vw, 600px"></p>
""",
  """
<h3><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">3. If you choke for a week, lower the difficulty</font></font></strong></h3>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Friday Night Funkin 'is a game that </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">requires a lot of skill</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> . </font><font style="vertical-align: inherit;">If some week it becomes impossible for you, do not be ashamed to </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">lower the difficulty level</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> . </font><font style="vertical-align: inherit;">Thanks to this, you will not only improve in the game but you will also become familiar with the musical tracks, being much easier to complete them in higher difficulty modes.</font></font></p>
<p><img loading="lazy" class="alignnone wp-image-218696" src="https://articles-img.sftcdn.net/images/w_600,h_350/v1610652256/friday_night_funkin_3_spgybk/friday_night_funkin_3_spgybk.jpg" alt="Friday Night Funkin Difficulty" width="600" height="350" srcset="https://articles-img.sftcdn.net/images/v1610652256/friday_night_funkin_3_spgybk/friday_night_funkin_3_spgybk.jpg 839w, https://articles-img.sftcdn.net/images/w_300,h_175,c_scale/v1610652256/friday_night_funkin_3_spgybk/friday_night_funkin_3_spgybk-300x175.jpg 300w, https://articles-img.sftcdn.net/images/w_768,h_448,c_scale/v1610652256/friday_night_funkin_3_spgybk/friday_night_funkin_3_spgybk-768x448.jpg 768w, https://articles-img.sftcdn.net/images/w_150,h_87,c_scale/v1610652256/friday_night_funkin_3_spgybk/friday_night_funkin_3_spgybk-150x87.jpg 150w" sizes="(max-width: 709px) 85vw, (max-width: 909px) 67vw, (max-width: 984px) 61vw, (max-width: 1362px) 45vw, 600px"></p>
""",
  """
<h3><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">4. Leave your mind blank&nbsp;</font></font></strong></h3>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">There is no greater enemy in a rhythm game than having a busy mind. </font><font style="vertical-align: inherit;">If you want to win all your fights, we recommend that you leave your mind blank and simply let yourself be guided by the music and the arrows that appear on the screen. </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Don't think, just act.</font></font></strong></p>
<p><img loading="lazy" class="alignnone wp-image-218697" src="https://articles-img.sftcdn.net/images/w_600,h_319/v1610652504/friday_night_funkin_4_nnpepq/friday_night_funkin_4_nnpepq.jpg" alt="Friday Night Funkin 'Week 4" width="600" height="319" srcset="https://articles-img.sftcdn.net/images/v1610652504/friday_night_funkin_4_nnpepq/friday_night_funkin_4_nnpepq.jpg 931w, https://articles-img.sftcdn.net/images/w_300,h_160,c_scale/v1610652504/friday_night_funkin_4_nnpepq/friday_night_funkin_4_nnpepq-300x160.jpg 300w, https://articles-img.sftcdn.net/images/w_768,h_408,c_scale/v1610652504/friday_night_funkin_4_nnpepq/friday_night_funkin_4_nnpepq-768x408.jpg 768w, https://articles-img.sftcdn.net/images/w_150,h_80,c_scale/v1610652504/friday_night_funkin_4_nnpepq/friday_night_funkin_4_nnpepq-150x80.jpg 150w" sizes="(max-width: 709px) 85vw, (max-width: 909px) 67vw, (max-width: 984px) 61vw, (max-width: 1362px) 45vw, 600px"></p>
""",
  """
<h3><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">5. Memorize the musical combos that cost you</font></font></strong></h3>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Can't get past Week 2? </font><font style="vertical-align: inherit;">A good trick to overcome the most frustrating levels is </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">to memorize the combos little by little</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> . </font><font style="vertical-align: inherit;">Although it is a slow method, you will see how by repeating the songs you will improve and you will be able to defeat all your rivals without effort.</font></font></p>
<p><img loading="lazy" class="alignnone wp-image-218698" src="https://articles-img.sftcdn.net/images/w_600,h_358/v1610652908/friday_night_funkin_5_dxqshq/friday_night_funkin_5_dxqshq.jpg" alt="Friday Night Funkin 'Week 2" width="600" height="358" srcset="https://articles-img.sftcdn.net/images/v1610652908/friday_night_funkin_5_dxqshq/friday_night_funkin_5_dxqshq.jpg 886w, https://articles-img.sftcdn.net/images/w_300,h_179,c_scale/v1610652908/friday_night_funkin_5_dxqshq/friday_night_funkin_5_dxqshq-300x179.jpg 300w, https://articles-img.sftcdn.net/images/w_768,h_458,c_scale/v1610652908/friday_night_funkin_5_dxqshq/friday_night_funkin_5_dxqshq-768x458.jpg 768w, https://articles-img.sftcdn.net/images/w_150,h_89,c_scale/v1610652908/friday_night_funkin_5_dxqshq/friday_night_funkin_5_dxqshq-150x89.jpg 150w" sizes="(max-width: 709px) 85vw, (max-width: 909px) 67vw, (max-width: 984px) 61vw, (max-width: 1362px) 45vw, 600px"></p>
""",
  """
<div id="NativeAd"></div>
""",
  """
<h3><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">6. Practice, practice, practice</font></font></h3>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">As in any rhythm game, to improve you must </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">practice as much as you can. </font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Do not forget that it is a game of skill and coordination, so the more time you dedicate, the better it will be.</font></font></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">We hope our </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Friday Night Funkin 'tips guide</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> has been helpful to you. </font><font style="vertical-align: inherit;">Do you know of any other tricks that we have not told? </font><font style="vertical-align: inherit;">Share it with us in the comment section!</font></font></p>
<p><img loading="lazy" class="alignnone wp-image-218699" src="https://articles-img.sftcdn.net/images/w_600,h_339/v1610653300/friday_night_funkin_6_xsbsyt/friday_night_funkin_6_xsbsyt.jpg" alt="Daddy Dearest on Friday Night Funkin '" width="600" height="339" srcset="https://articles-img.sftcdn.net/images/v1610653300/friday_night_funkin_6_xsbsyt/friday_night_funkin_6_xsbsyt.jpg 898w, https://articles-img.sftcdn.net/images/w_300,h_169,c_fill,g_auto/v1610653300/friday_night_funkin_6_xsbsyt/friday_night_funkin_6_xsbsyt-300x169.jpg 300w, https://articles-img.sftcdn.net/images/w_768,h_433,c_fill,g_auto/v1610653300/friday_night_funkin_6_xsbsyt/friday_night_funkin_6_xsbsyt-768x433.jpg 768w, https://articles-img.sftcdn.net/images/w_800,h_450,c_fill,g_auto/v1610653300/friday_night_funkin_6_xsbsyt/friday_night_funkin_6_xsbsyt-800x450.jpg 800w, https://articles-img.sftcdn.net/images/w_664,h_374,c_fill,g_auto/v1610653300/friday_night_funkin_6_xsbsyt/friday_night_funkin_6_xsbsyt-664x374.jpg 664w, https://articles-img.sftcdn.net/images/w_238,h_134,c_fill,g_auto/v1610653300/friday_night_funkin_6_xsbsyt/friday_night_funkin_6_xsbsyt-238x134.jpg 238w, https://articles-img.sftcdn.net/images/w_436,h_246,c_fill,g_auto/v1610653300/friday_night_funkin_6_xsbsyt/friday_night_funkin_6_xsbsyt-436x246.jpg 436w, https://articles-img.sftcdn.net/images/w_370,h_208,c_fill,g_auto/v1610653300/friday_night_funkin_6_xsbsyt/friday_night_funkin_6_xsbsyt-370x208.jpg 370w, https://articles-img.sftcdn.net/images/w_150,h_85,c_scale/v1610653300/friday_night_funkin_6_xsbsyt/friday_night_funkin_6_xsbsyt-150x85.jpg 150w" sizes="(max-width: 709px) 85vw, (max-width: 909px) 67vw, (max-width: 984px) 61vw, (max-width: 1362px) 45vw, 600px"></p>
"""
];